# threading

In [1]:
import threading

In [2]:
threading.active_count(), threading.enumerate(), threading.current_thread()

(5,
 [<_MainThread(MainThread, started 68744)>,
  <Thread(Thread-4, started daemon 1984)>,
  <Heartbeat(Thread-5, started daemon 80572)>,
  <HistorySavingThread(IPythonHistorySavingThread, started 80856)>,
  <ParentPollerWindows(Thread-3, started daemon 81684)>],
 <_MainThread(MainThread, started 68744)>)

## join 等待

In [3]:
import time
import threading

In [4]:
# main 執行完，T1還在執行，在jupyter 就被咖掉了
def T1_job():
    print("T1 start\n")
    for i in range(10):
        time.sleep(0.1)  # T1會執行比較久
    print("T1 finish\n")

def T2_job():
    print("T2 start\n")
    print("T2 finish\n")

thread_1 = threading.Thread(target=T1_job, name='T1')
thread_2 = threading.Thread(target=T2_job, name='T2')

thread_1.start() 
thread_2.start() 

print("all done\n")  

T1 start

T2 start

T2 finish

all done



In [5]:
# 加上join 等待
def T1_job():
    print("T1 start\n")
    for i in range(10):
        time.sleep(0.1)  # T1會執行比較久
    print("T1 finish\n")

def T2_job():
    print("T2 start\n")
    print("T2 finish\n")

thread_1 = threading.Thread(target=T1_job, name='T1')
thread_2 = threading.Thread(target=T2_job, name='T2')

thread_1.start() 
thread_2.start() 

thread_1.join() # 等T1執行完才繼續下面的程式
print("all done\n")

T1 start

T2 start

T2 finish

T1 finish

T1 finish

all done



## Queue 可以有return

In [6]:
import queue
import threading
import numpy as np

In [7]:
def job(l, q):
    for i in range(len(l)):
        l[i] = l[i]**2
    q.put(l)  # return 存進這

In [8]:
# multithreading
num_threads = 4

q = queue.Queue()
threads = []
result = []
data = np.array([[1, 2, 3], 
                 [3, 4, 5], 
                 [4, 4, 4], 
                 [5, 5, 5]])


for i in range(num_threads):   
    t = threading.Thread(target=job,args=(data[i], q))
    t.start()  # 開始
    threads.append(t)
    
# 等待全部線程執行完    
for i in range(num_threads):    
    t.join()  
    
# 取出result
for i in range(num_threads):
    result.append(q.get())

result = np.array(result)
print(result)

[[ 1  4  9]
 [ 9 16 25]
 [16 16 16]
 [25 25 25]]


## GIL (Global Interpreter Lock)

拜它所賜，在python開多線程不一定會比較快(可能還比較慢)，在I/O比較多的case，才會比較快

In [9]:
import copy
import time
import threading

from queue import Queue

In [10]:
def job(l, q):
    res = sum(l)
    q.put(res)

In [11]:
def multithreading(l, num_threads=10):
    q = Queue()
    threads = []
    for i in range(num_threads):
        t = threading.Thread(target=job, args=(copy.copy(l), q), name='T%i' % i)     
        t.start()
        threads.append(t)

    [t.join() for t in threads]
    
    total = 0
    for _ in range(num_threads):
        total += q.get()


def normal(l):
    total = sum(l)

In [12]:
l = list(range(1000000))

s_t = time.time()
normal(l*4)
print(f'normal: {time.time()-s_t: .2f}')

s_t = time.time()
multithreading(l, num_threads=10)
print(f'10 threading: {time.time()-s_t:.2f}')

s_t = time.time()
multithreading(l, num_threads=2)
print(f'2 threading: {time.time()-s_t:.2f}')

normal:  0.10
10 threading: 0.24
2 threading: 0.05


## lock